apiVersion: batch/v1
kind: CronJob
metadata:
  name: 4helm-cronjob
  namespace: exercise
spec:
  schedule: "*/5 * * * *"
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app: 4helm
        spec:
          restartPolicy: OnFailure
          containers:
            - name: 4helm
              image: hashicorp/http-echo:0.3.1
              args:
                - "-text=Hello from CronJob"