apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: 4helm-daemonset
  namespace: exercise
spec:
  selector:
    matchLabels:
      app: 4helm
  template:
    metadata:
      labels:
        app: 4helm
    spec:
      containers:
        - name: 4helm
          image: hashicorp/http-echo:0.3.1
          args:
            - "-text=Hello from DaemonSet"
          ports:
            - containerPort: 5678