apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.app.name }}-deployment
  namespace: {{ .Values.namespace }}  #exercise
spec:
  replicas: {{ .Values.replicaCount }} #2
  selector:
    matchLabels:
      app: {{ .Values.app.name }}  #4helm
  template:
    metadata:
      labels:
        app: {{ .Values.app.name }}  #4helm
    spec:
      containers:
        - name: {{ .Values.app.name }}  #4helm
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }} #hashicorp/http-echo:0.3.1
          args:
            - "-text=Hello from Deployment"
          ports:
            - containerPort: 5678