# Default values for 4helm.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

app:
  name: 4helm

image:
  repository: hashicorp/http-echo
  tag: 0.3.1

replicaCount: 2
namespace: exercise



