# Default values for 4helm.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 2

image:
  repository: hashicorp/http-echo:0.3.1
  pullPolicy: IfNotPresent

